{% set name = "tbump" %}
{% set version = "6.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tbump-{{ version }}.tar.gz
  sha256: 9ebf5d69bc92ca8be1afb13a80f51e374526cb9988f4c3b167036a9e8a10a684

build:
  number: 1
  noarch: python
  entry_points:
    - tbump = tbump.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - cli-ui >=0.10.3
    - docopt >=0.6.2
    - python >={{ python_min }},<4.0
    - schema >=0.7.1
    - tomlkit >=0.5.8

test:
  imports:
    - tbump
  commands:
    - pip check
    - tbump --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dmerejkowsky/tbump
  summary: Bump software releases
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dmerejkowsky
    - umonaca
